name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Tests for the template
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install .
      - run: pip install '.[dev]'
      - run: pytest
  cookie: # Generate project, run CI & build docs
    strategy:
      fail-fast: false
      matrix:
        script:
          - { run: pytest, dir: "" }
          - { run: flake8 ., dir: "cookiecutter-pyproject" }
          - { run: black --check ., dir: "" }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: pip install .
      - run: pip install '.[dev]'
      - name: Run ${{ matrix.script.run }}
        run: ${{ matrix.script.run }}
